### ISSUE TITLE
How to generate 12 digits

### ISSUE THREAD

**Issue by BI7PRK** [RobThree/IdGen#10]
Hi, I want to batch generation12 digits Ids. max count about 100M. how to set the configs?
thank you!

**Comment by RobThree** [comment]
What are 'generation12 digits Ids'? If you're referring to max. 12 digits sequences, that would be:

`999.999.999.999` => `1110_1000_1101_0100_1010_0101_0000_1111_1111_1111` which is 40bits. So if you set the sequence part of the mask to 39 bits (`111_1111_1111_1111_1111_1111_1111_1111_1111_1111`) you will never exceed `549.755.813.887` **in the sequence** part. The rest of the bits (63 - 39 = 24) can then be used for the timestamp and generator id.

If wou want to generate 12 digits max. **total** with sequences of max. 100.000.000 then you'd have to set the sequence part to `99.999.999` => `101_1111_0101_1110_0000_1111_1111` which gives max. 26 bits `11_1111_1111_1111_1111_1111_1111` => 67.108.863. The rest of 13 bits (39 - 26 = 13) could then be used for the timestamp and generator part. Assuming you take 0 bits for the generator, that leaves 13 bits for the timestamp which gives 8192 intervals. If you use a timesource with a resolution of seconds you'll run out of ID's in less than 2.5 hours. If you use a resolution of hours you'll run out of id's in less than a year.

But there's a bigger problem here: IdGen requires the maskconfig to be exactly 63 bits to ensure maximum usage of all bits available for the largest possible combinations of generators, sequences and timestamps. IdGen *always* generates 64 bit Id's (where the [MSB](https://en.wikipedia.org/wiki/Bit_numbering#Most_significant_bit) is always 0, so essentially 63 bit Id's). So even if you would configure IdGen to use only 39 bits you'd have to fork and make your own build removing the [63 bit requirement](https://github.com/RobThree/IdGen/blob/306ba56bd12981313747c8009776582a8f6b65db/IdGen/IdGenerator.cs#L148).

My question to you, though, is: why have such a strange requirement of max. 12 digits in the first place? Are you sure you understand what IdGen's intented use is? IdGen is intended to have multiple servers/processes/threads generate Id's and guaranteeing that there will be no 'collisions' with other servers/processes/threads instead of each generating some random number with the chance of a collision. And that IdGen generates (roughly, when used with more than 1 generator) incremental Id's, which are much friendlier to indexes, instead of 'random' Id's like UUID's / GUID's. IdGen is meant to be used in _very specific situations_ (mostly in '[distributed](https://en.wikipedia.org/wiki/Distributed_computing)' scenario's), not as a generic Id generator.

Having said that; there **is** a way that might satisfy your question. You could still use the entire 63 bits and use 26 bits for 100M sequences and use the other bits for generators and timestamps. "But that would generate Id's of max. 19 digits!" I hear you say. Correct. But that would only be true if you write down the Id in base 10. There's nothing stopping you from using another base, like [Base64](https://en.wikipedia.org/wiki/Base64) as long as you don't mind alphanumeric Id's. The max. 63 bit value that IdGen will ever generate is `9223372036854775807` which is `/////////38` in base64 and which is 11 "<strike>digits</strike> characters". (Granted, this specific value looks a bit shitty, but generally, Id's would look like `AAAAg3RCwAY`). This is, sort of, what YouTube does for example with it's [video Id's](https://www.youtube.com/watch?v=gocwRvLhDf8). If you strip of the [padding](https://en.wikipedia.org/wiki/Base64#Output_padding) which is optional and use a [variant](https://en.wikipedia.org/wiki/Base64#Variants_summary_table) that uses the characters you like (or implement your own variant) then you're good to go and never get Id's with more than 12 "digits". *Do* note, however, that *storing* a "Base64 encoded Id" will require 11 bytes when stored as string/varchar whereas a "normal" 63 bit Id will require only 8 bytes since 8 bytes fit 64 bits. Another option would be [Base32](https://en.wikipedia.org/wiki/Base32) but that would give, at most, 13 digits (max. `77777777777X6`).

**Comment by BI7PRK** [comment]
Thank you so much for your detailed answer. the content of English is challenging for me. but I probably understand your explanation.
my using  scene is:
- Generate 18 digits unpredictable numbers
- 12 digits is a sequenced ID, 6 digits are random

Maybe I will think about other options.
Thanks!

**Comment by RobThree** [comment]
> [...] unpredictable numbers
> [...] 6 digits are random

Then **don't use IdGen**. IdGen is 100% [deterministic](https://en.wikipedia.org/wiki/Deterministic_system#In_computer_science); nothing random or unpredictable about it.
