### ISSUE TITLE
Avoid spending a sign bit by using ulongs

### ISSUE THREAD

**Issue by velddev** [RobThree/IdGen#41]
Hey, would it be possible to create a way to use AddIdGen which uses ulongs instead of longs instead to avoid wasting a single bit on the sign modifier?

**Comment by RobThree** [comment]
Only if you fork 😜 

As explained in [How It Works](https://github.com/RobThree/IdGen#how-it-works):

> The [Sign Bit](https://en.wikipedia.org/wiki/Sign_bit) is unused since this can cause incorrect ordering on some systems that cannot use unsigned types and/or make it hard to get correct ordering.

So this is intentional. I guess we could make it opt-in by adding an option to [IdStructure](https://github.com/RobThree/IdGen/blob/master/IdGen/IdStructure.cs) (i.e. `UseSignBit` or something) but I don't think there's very much demand for it.

Are you trying to solve a problem and, if so, what is the problem? Maybe I can give some other helpful advice or provide a workaround or alternative.

**Comment by rmandvikar** [comment]
Apart from 2x'ing the range, the last bit could be used for versioning. :shrug:

**Comment by RobThree** [comment]
> Apart from 2x'ing the range, the last bit could be used for versioning. 🤷

It could, I am aware. But again:

> this can cause incorrect ordering on some systems that cannot use unsigned types and/or make it hard to get correct ordering.

Also, one can ask oneself how 1 bit is useful in versioning...

**Comment by rmandvikar** [comment]
That's the only bit that's unused, and you only get 2 versions, so one needs to choose wisely. 😅

I'll be using this nuget in another app shortly, and i wanted to see if I could distinguish between the ids genned by the apps, and this came to my mind. I understand that I could fiddle around with the generator-id bits, but I would have to change few things first.

**Comment by RobThree** [comment]
> distinguish between the ids genned by the apps

That's what the generator bits are for. Assign each app a unique generator-id (assuming 10 bits you can have 1024 apps/generators) and that way you'll be able to distinguish which app generated which ID.

**Comment by boraturant** [comment]
I think full 64 bit (uLong) id option would be nice. Many projects would design for 2x capacity, and people would be aware to store it in unsigned fields in dbs

**Comment by RobThree** [comment]
For 3rd parties consuming such ID's it may not always be apparent that ID's are unsigned. It's very reasonable to assume that when someone sees an id like `862817670527975424` to just assume "long" and move on. The reason for this design decision is very deliberate and [documented](https://github.com/RobThree/IdGen#how-it-works) and [quoted earlier](https://github.com/RobThree/IdGen/issues/41#issuecomment-1437282953):

> this can cause incorrect ordering on some systems that cannot use unsigned types and/or make it hard to get correct ordering.

If you want unsigned ulongs I suggest you fork the project and make it happen 😉

**Comment by boraturant** [comment]
Thank you for your comment, trying to fork, confused on how to change the below line, do you have advise for this?

    private static long GetMask(byte bits) => (1L << bits) - 1;

**Comment by RobThree** [comment]
You're gonna have to start with changing [`IdStructure`](https://github.com/RobThree/IdGen/blob/3d388f4d46cb529c138816f87e35ce7deac5df0f/IdGen/IdStructure.cs#L54). I don't see why you'd change the GetMask function?

**Comment by boraturant** [comment]
thanks, I assumed 'long' and '1L' would have to be changed.

**Comment by danielgindi** [comment]
I'm curious... Which systems do not correctly support unsigned int64? I mean, it's been 30 years since 64 bit cpus have been introduced.

**Comment by RobThree** [comment]
[Again](https://github.com/RobThree/IdGen/issues/41#issuecomment-1427047673), it's not about wether it being supported by CPU's; it's about infrastructure or systems used in conjunction with an IdGen id that _may_ not have support for unsigned values altogether (like RDBMS'es such as [PostgresSQL](https://www.postgresql.org/docs/16/datatype-numeric.html), or simply [Java](https://www.nayuki.io/page/unsigned-int-considered-harmful-for-java) or Python IIRC). When an unsigned value would be stored in such a system it would be interpreted as a negative value, drastically changing the meaning and sort-order of the value. For safety, the bit is ignored. We're not bound by what systems IdGen is run on (basically, any machine capable of running .Net code) but by any and all systems that will have to handle the produced ID's. Finally, IdGen is based on, and is compatible with, (then) [Twitter's Snowflake algorithm](https://en.wikipedia.org/wiki/Snowflake_ID#Format), which also used 63 bits.

Personally I've even ran into issues several times because Javascript can't even handle 63 bit integers properly and I needed to represent them as strings. This has bitten me more than once.

**Comment by danielgindi** [comment]
Well, Java historically did not support unsigned, but latest Java and Kotlin do (considered experimental).
As for python - no unsigned yet.
Javascript uses a 64-bit floating point type natively, and only support unsigned arrays (`BigUInt64Array`). *But* both Facebook and Twitter always represented those ids as strings when going in and out the api. The same could be done for python, old Java, or any other consumer.

Actually, the fact that you say it's not about being supported by the CPU which generates the ID - makes the argument against the 64th bit pointless. Because anything else that only *uses* the IDs, would have to use string representations anyway - because of JS consumers most definitely exists.
And 63 bits do not solve that for JS - as whole numbers could be represented only up to 53 bits when stored in 64-bit floats.

So you could see why I was raising this here again. Your original explanation just does not make sense to me, considering all the above.

The only exception to that is probably Postgresql, for which the devs were too lazy to add unsigned support yet. But I assume (hope?) that that would get fixed too, sometime in the future.

Anyway, thanks for a neat library!
