### ISSUE TITLE
Sequence input for CreateId()

### ISSUE THREAD

**Issue by boraturant** [RobThree/IdGen#57]
I would like to input my custom sequence id. Could this be supported?  I know the implications, but I want to input sequence into the function in a similar setting how Instagram creates UIDs > https://instagram-engineering.com/sharding-ids-at-instagram-1cf5a71e5a5c

**Comment by RobThree** [comment]
That's currently not supported and I don't see how this should be implemented in a generic way without sacrificing a lot of performance. You'd need to have an `IGeneratorProvider` which would return the 'shard' or 'generator' which would have to take some arbitrary value as input to be able to do it's work and then you'd also need an `ISequenceProvider` which would need a similar arbitrary input. That would, in turn, mean that `CreateId()` would need to be able to take some argument(s) etc.

Suggestions are welcome, but I don't see how this would be implemented without a major rewrite and/or breaking backcompat.

Also: since you're _specifically_ asking for sequence: adding a `modulo <value>` essentially means "wrap around" which would result in collisions...

**Comment by boraturant** [comment]
maybe something like simple CreateIdWithSequenceInput(long sequence) - without changing the CreateId() - however, I guess lenght has to be checked with  sequence input and mask capacity for sequence. Regarding the modulo, I guess it should be the callers responsibility inputing the modulo-ed sequence value.

thank you for your feedback!

**Comment by RobThree** [comment]
> Regarding the modulo, I guess it should be the callers responsibility inputing the modulo-ed sequence value.

Isn't it easier, at that point, to implement your "own IdGen"? It isn't exactly rocket surgery, as you can see in the instagram post.
