### ISSUE TITLE
IIdGenerator is registered as a singleton, but duplicate IDs are still generated

### ISSUE THREAD

**Issue by andrew2558** [RobThree/IdGen#58]
```csharp
//services.AddIdGen(258);
services.AddSingleton<IIdGenerator<long>>(c => new IdGenerator(258));
```

controller：
```csharp
private readonly IdGenerator _idGen;
public LearnHistoryController( IdGenerator idGen)
{
            _idGen = idGen;
 }
```

action use code:
```
public ApiResponse GetSnowId(int count)
{
            return SuccessResult(_idGen.Take(count));
}
```

<img width="223" alt="image" src="https://github.com/RobThree/IdGen/assets/25080605/1dd2ba65-8ab1-46ec-a5ff-140e701b41e6">

What went wrong? thanks

**Comment by RobThree** [comment]
I have no idea, it [works](https://dotnetfiddle.net/9uxj2M) for me when I use it directly and when I [get it from DI](https://dotnetfiddle.net/R6RA2i) (which shouldn't make a difference anyway).

Is there something else worth mentioning about your project that might be relevant?

**Comment by andrew2558** [comment]
thanks, @RobThree 
The above is the whole code, I don't know what went wrong
The attachment is the test code, which also has the same problem.

[IdGenTest.zip](https://github.com/RobThree/IdGen/files/12882176/IdGenTest.zip)

**Comment by RobThree** [comment]
Oh, hahah! I get it. This is actually mentioned in our [FAQ](https://github.com/RobThree/IdGen#faq):

> # FAQ
>
> **Q**: I'm experiencing weird results when these ID's are used in Javascript?
>
> **A**: Remember that generated ID's are 64 (actually 63) bits wide. Javascript uses floats to store all numbers and the [maximum integer value you can safely store](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) is 53 bits. If you need to handle these ID's in Javascript, treat them as `strings`.

The problem is with Swagger / Json interpreting the ID's as doubles. Look at the actual response:

![image](https://github.com/RobThree/IdGen/assets/607888/ef18ffbd-8b2d-4164-a3c8-ae5df5a69308)

There's nobody at fault here really, it's just the way browsers/JS handle numbers (as described in our FAQ). The values you see are "rounded" to the nearest 53-bit float. If you don't want this to happen then, _in a browser context_, you should convert your ID's to strings:

```c#
[HttpGet("GetIds")]
public ActionResult GetIds(int idCount)
{
    return Ok(_idGenerator.Take(idCount).Select(i => i.ToString()));
}
```

![image](https://github.com/RobThree/IdGen/assets/607888/fb1e890f-d7f0-4785-86e7-5bfe1d2d4f1e)

**Comment by andrew2558** [comment]
Thank your very much @RobThree
