### ISSUE TITLE
Provide id into [timestamp ,generatorId ,sequence]?

### ISSUE THREAD

**Issue by shuaqq2004** [RobThree/IdGen#7]
` var generator = new IdGenerator(0);`
`  var id = generator.CreateId();`
`var genData = generator.FromId(id); //add this method?`
I want to know when Id was generated。

**Comment by RobThree** [comment]
That's a very dangerous method; since you can't know for sure with what mask or timestamp-resolution the id was generated. Assuming you'd be willing to assume those variables are "fixed" in your project then, yes, that would be a possibility. But why (ab)use an ID for this and not simply (also) store a timestamp?

**Comment by RobThree** [comment]
Despite my initial reluctancy I decided to [include it in 2.0.3](https://www.nuget.org/packages/IdGen/2.0.3). See [here](https://github.com/RobThree/IdGen/blob/6f26d44df8287282b40a06530acf2dfaa2a9fe9f/IdGen/IdGenerator.cs#L222). I've decided not to include it in the [`IIdGenerator`](https://github.com/RobThree/IdGen/blob/6f26d44df8287282b40a06530acf2dfaa2a9fe9f/IdGen/IIdGenerator.cs) interface (yet).
