### ISSUE TITLE
What's wrong with this code？

### ISSUE THREAD

**Issue by xingwen1987** [RobThree/IdGen#8]
[https://www.cnblogs.com/yushuo/p/9406906.html](https://www.cnblogs.com/yushuo/p/9406906.html)
Using Twitter's Snowflake to generator unique id,but there is a serious repetition

**Comment by RobThree** [comment]
> What's wrong with this code

Oh, boy, where do I start...

Well: first of all it's not my code. I don't see why I'm supposed to debug someone else's code. But then again, I go by a tariff of €120,- p/hr and then I'm glad to pour over your code.

Second: It's all in Chinese. I can read the code fine but the comments are, literally, Chinese to me. So that makes it... challenging.

Third: The code is not posted in the issue / on github but on some external site. So even if I were to give you a free code review, the link will most probably be gone in a while and then the only person who profited from all my hard (free) work would be you. All knowledge I might have shared with you wouldn't make sense without the code I was referring to and so my shared knowledge would be lost and worthless.

Fourth: It's not even related to IdGen but much more closer to Twitter's original snowflake project. I don't see why you don't approach the original authors but me?

Fifth: You don't describe the problem. "What's wrong with this code" is not a problem description. It's like taking your car to the garage and asking a mechanic what's wrong with it. How is he/she supposed to know? Unless you're missing a wheel or there's black smoke billowing out the hood, how is he ever supposed to find the broken cigarette lighter you're referring to but not telling him about? You're mentioning "serious repetition" but, again, explain nothing (unless you expect me to read Chinese...)

Lasty: I don't see **any** effort you might have taken to troubleshoot / debug the problem **yourself**. You appear to have simply googled "Snowflake", come across this project, and dumped your question here in my lap expecting me to debug / troubleshoot your code, which is mostly unreadable to me, for free. Not gonna happen. The **very least** you could have done was include your own findings or steps you have taken to troubleshoot your problem.

Maybe try [codereview.stackexchange.com](https://codereview.stackexchange.com/) next time.

But hey, if you're having trouble implementing Snowflake, maybe try [IdGen](https://github.com/RobThree/IdGen)? 😉 

...and did you remember to change the `MachineId` (and/or `DatacenterId` for each machine)?
